### ISSUE TITLE
la fonction sauvegarde dans Moteur/verifcoup.py ne s'effectue pas

### ISSUE THREAD

**Issue by Chat-mots** [ritorizo/nsi-echec#4]
peut être que je suis juste attardé, mais la fonction sauvegarde marche très bien toute seul, mais je n'arrive pas à l'effectuer avec la fonction verifcoup.py

**Comment by Minemew2** [comment]
Peut être cher Victor que pour utiliser une fonction, il faut l'appeler (crétin) <3
